name: Climate and Carbon Cognizance
description: Run my Streamlit application.
author: Jay Jain
specification_version: 1.0
prototype_version: 1.0
date: "2024-03-07"

runtimes:
  - editor: Workbench ## Other acceptable values are determined by the runtimes available in your CML environment
    kernel: Python 3.10 ## Same here, check your runtimes (custom runtimes can be added as well)
    edition: Standard ## Particularly relevant if using GPUs, Nvidia GPU

## Below are some sample tasks based on some of the most popular aspects of AMP creation.
tasks:
  ## SESSION related AMP snippet
  - type: run_session
    name: Install Dependencies
    script: scripts/install_dependencies.py
    short_summary: Install Requirements and Dependencies
    kernel: python3
    cpu: 2
    memory: 4

  ## JOB related AMP snippet
  - type: start_application
    short_summary: Starting Streamlit application
    name: Climate and Carbon Cognizance
    subdomain: streamlit
    script: scripts/launch_app.py
    environment:
      TASK_TYPE: START_APPLICATION
    cpu: 2
    memory: 4
